name       : perl-archive-extract
version    : 0.8
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/B/BI/BINGOS/Archive-Extract-0.80.tar.gz : 25cbc2d5626c14d39a0b5e4fe8383941e085c9a7e0aa873d86e81b6e709025f4
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : A generic archive extraction module
description: |
    Archive::Extract is a generic archive extraction mechanism.
    It allows you to extract .tgz, .tar, .gz and .zip files, using either perl modules or commandline tools
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %make test
