name       : perl-archive-extract
version    : '0.86'
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/B/BI/BINGOS/Archive-Extract-0.86.tar.gz : 9acd09cdb8e8cf0b6d08210a3b80342300c89a359855319bf6b00c14c4aab687
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : A generic archive extraction module
description: |
    Archive::Extract is a generic archive extraction mechanism.
    It allows you to extract .tgz, .tar, .gz and .zip files, using either perl modules or commandline tools
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %make test
